bot:
  name: bot_matyuk_bot
  token: 5662992371:AAGlFeJI8MBMkDFW3Mq-2jMyXAISdeT1deI

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: a2jcyccz4
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace