spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

learning:
  count_successful: 3

