package ru.matyuk.irregularVerbsBot.enums;

public enum StateUser {
    REGISTERED_STATE,
    VIEW_GROUP_STATE,
    CHOOSE_GROUP_STATE,
    START_LEARN_STATE,
    LEARNING_IN_PROCESS_STATE,
    CREATE_GROUP_STATE,
    SET_NAME_GROUP_STATE,
    DELETE_GROUP_STATE;


}
