package ru.matyuk.irregularVerbsBot.enums;

public enum StateUser {

    MAIN_MENU_STATE,
    VIEW_GROUP_STATE,
    CHOOSE_GROUP_STATE,
    SETTING_GROUP_STATE,
    DELETE_GROUP_STATE,
    CREATE_GROUP_STATE,
    LEARNING_STATE,
    CREATE_FEEDBACK_STATE,
    CONFIRM_VERBS_IN_GROUP_STATE,
    SET_NAME_GROUP_STATE,
    ALL_DELETE_STATE;


}
